// Copyright 2026 printing-press-golden. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package mcp

import (
	"context"
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"time"

	mcplib "github.com/mark3labs/mcp-go/mcp"
	"github.com/mark3labs/mcp-go/server"
	"printing-press-golden-pp-cli/internal/cliutil"
	"printing-press-golden-pp-cli/internal/client"
	"printing-press-golden-pp-cli/internal/config"
	"printing-press-golden-pp-cli/internal/store"
)

// RegisterTools registers all API operations as MCP tools.
func RegisterTools(s *server.MCPServer) {
	s.AddTool(
		mcplib.NewTool("projects_create",
			mcplib.WithDescription("Create project Returns Project."),
		),
		makeAPIHandler("POST", "/projects", []string{ }),
	)
	s.AddTool(
		mcplib.NewTool("projects_get",
			mcplib.WithDescription("Get project"),
			mcplib.WithString("projectId", mcplib.Required(), mcplib.Description("Project id")),
		),
		makeAPIHandler("GET", "/projects/{projectId}", []string{"projectId", }),
	)
	s.AddTool(
		mcplib.NewTool("projects_list",
			mcplib.WithDescription("List projects Returns array of Project."),
			mcplib.WithString("status", mcplib.Description("Status")),
			mcplib.WithString("limit", mcplib.Description("Limit")),
			mcplib.WithString("cursor", mcplib.Description("Cursor")),
		),
		makeAPIHandler("GET", "/projects", []string{ }),
	)
	s.AddTool(
		mcplib.NewTool("projects_tasks_list-project",
			mcplib.WithDescription("List project tasks Returns array of Task."),
			mcplib.WithString("projectId", mcplib.Required(), mcplib.Description("Project id")),
			mcplib.WithString("priority", mcplib.Description("Priority")),
			mcplib.WithString("limit", mcplib.Description("Limit")),
			mcplib.WithString("cursor", mcplib.Description("Cursor")),
		),
		makeAPIHandler("GET", "/projects/{projectId}/tasks", []string{"projectId", }),
	)
	s.AddTool(
		mcplib.NewTool("projects_tasks_update-project",
			mcplib.WithDescription("Update project task Partial update."),
			mcplib.WithString("projectId", mcplib.Required(), mcplib.Description("Project id")),
			mcplib.WithString("taskId", mcplib.Required(), mcplib.Description("Task id")),
		),
		makeAPIHandler("PATCH", "/projects/{projectId}/tasks/{taskId}", []string{"projectId","taskId", }),
	)
	s.AddTool(
		mcplib.NewTool("public_get-status",
			mcplib.WithDescription("Get public service status (public)"),
		),
		makeAPIHandler("GET", "/public/status", []string{ }),
	)
	s.AddTool(
		mcplib.NewTool("reports_summary_get-report-year",
			mcplib.WithDescription("Get a report summary for a year"),
			mcplib.WithString("year", mcplib.Required(), mcplib.Description("Year")),
		),
		makeAPIHandler("GET", "/reports/{year}/summary", []string{"year", }),
	)
	// Sync tool — populates local database for offline search and sql queries
	s.AddTool(
		mcplib.NewTool("sync",
			mcplib.WithDescription("Sync API data to local SQLite database. Run this before using search or sql tools. Supports incremental sync."),
			mcplib.WithString("resources", mcplib.Description("Comma-separated resource types to sync (omit for all)")),
			mcplib.WithString("since", mcplib.Description("Incremental sync since duration (e.g. 7d, 24h, 1w)")),
			mcplib.WithBoolean("full", mcplib.Description("Full resync ignoring checkpoints")),
		),
		handleSync,
	)
	// SQL tool — ad-hoc analysis on synced data without API calls
	s.AddTool(
		mcplib.NewTool("sql",
			mcplib.WithDescription("Run read-only SQL against local database. Use for ad-hoc analysis, aggregations, and joins across synced resources. Requires sync first."),
			mcplib.WithString("query", mcplib.Required(), mcplib.Description("SQL query (SELECT only). Tables match resource names.")),
		),
		handleSQL,
	)

	// Context tool — front-loaded domain knowledge for agents.
	// Call this first to understand the API taxonomy, query patterns, and capabilities.
	s.AddTool(
		mcplib.NewTool("context",
			mcplib.WithDescription("Get API domain context: resource taxonomy, auth requirements, query tips, and unique capabilities. Call this first."),
		),
		handleContext,
	)
}

// makeAPIHandler creates a generic MCP tool handler for an API endpoint.
func makeAPIHandler(method, pathTemplate string, positionalParams []string) server.ToolHandlerFunc {
	return func(ctx context.Context, req mcplib.CallToolRequest) (*mcplib.CallToolResult, error) {
		c, err := newMCPClient()
		if err != nil {
			return mcplib.NewToolResultError(err.Error()), nil
		}

		// mcp-go v0.47+ made CallToolParams.Arguments an `any` to support
		// non-map payloads; GetArguments() returns the map[string]any shape
		// we rely on here (or an empty map when the payload is something else).
		args := req.GetArguments()

		// Build path by substituting positional params
		path := pathTemplate
		for _, p := range positionalParams {
			if v, ok := args[p]; ok {
				path = strings.Replace(path, "{"+p+"}", fmt.Sprintf("%v", v), 1)
			}
		}

		// Collect non-positional params as query params
		params := make(map[string]string)
		for k, v := range args {
			isPositional := false
			for _, p := range positionalParams {
				if k == p {
					isPositional = true
					break
				}
			}
			if !isPositional {
				params[k] = fmt.Sprintf("%v", v)
			}
		}

		var data json.RawMessage
		switch method {
		case "GET":
			data, err = c.Get(path, params)
		case "POST":
			body, _ := json.Marshal(args)
			data, _, err = c.Post(path, body)
		case "PUT":
			body, _ := json.Marshal(args)
			data, _, err = c.Put(path, body)
		case "PATCH":
			body, _ := json.Marshal(args)
			data, _, err = c.Patch(path, body)
		case "DELETE":
			data, _, err = c.Delete(path)
		default:
			return mcplib.NewToolResultError("unsupported method: " + method), nil
		}

		if err != nil {
			msg := err.Error()
			switch {
			case strings.Contains(msg, "HTTP 409"):
				return mcplib.NewToolResultText("already exists (no-op)"), nil
			case strings.Contains(msg, "HTTP 400") && cliutil.LooksLikeAuthError(msg):
				return mcplib.NewToolResultError("authentication error: " + cliutil.SanitizeErrorBody(msg) +
					"\nhint: the API rejected the request — this usually means auth is missing or invalid." +
					"\n      Set your API key: export PRINTING_PRESS_GOLDEN_API_KEY_AUTH=<your-key>" +
					"\n      Run 'printing-press-golden-pp-cli doctor' to check auth status."), nil
			case strings.Contains(msg, "HTTP 401"):
				return mcplib.NewToolResultError("authentication failed: " + cliutil.SanitizeErrorBody(msg) +
					"\nhint: check your API key." +
					"\n      Set it with: export PRINTING_PRESS_GOLDEN_API_KEY_AUTH=<your-key>" +
					"\n      Run 'printing-press-golden-pp-cli doctor' to check auth status."), nil
			case strings.Contains(msg, "HTTP 403"):
				return mcplib.NewToolResultError("permission denied: " + cliutil.SanitizeErrorBody(msg) +
					"\nhint: your credentials are valid but lack access to this resource." +
					"\n      Set it with: export PRINTING_PRESS_GOLDEN_API_KEY_AUTH=<your-key>" +
					"\n      Run 'printing-press-golden-pp-cli doctor' to check auth status."), nil
			case strings.Contains(msg, "HTTP 404"):
				if method == "DELETE" {
					return mcplib.NewToolResultText("already deleted (no-op)"), nil
				}
				return mcplib.NewToolResultError("not found: " + msg), nil
			case strings.Contains(msg, "HTTP 429"):
				return mcplib.NewToolResultError("rate limited: " + msg), nil
			default:
				return mcplib.NewToolResultError(msg), nil
			}
		}

		// For GET responses, wrap bare arrays with count metadata
		if method == "GET" {
			trimmed := strings.TrimSpace(string(data))
			if len(trimmed) > 0 && trimmed[0] == '[' {
				var items []json.RawMessage
				if json.Unmarshal(data, &items) == nil {
					wrapped := map[string]any{
						"count": len(items),
						"items": items,
					}
					out, _ := json.Marshal(wrapped)
					return mcplib.NewToolResultText(string(out)), nil
				}
			}
		}
		return mcplib.NewToolResultText(string(data)), nil
	}
}

func newMCPClient() (*client.Client, error) {
	home, _ := os.UserHomeDir()
	cfgPath := filepath.Join(home, ".config", "printing-press-golden-pp-cli", "config.toml")
	cfg, err := config.Load(cfgPath)
	if err != nil {
		return nil, fmt.Errorf("loading config: %w", err)
	}
	return client.New(cfg, 30*time.Second, 0), nil
}

func dbPath() string {
	home, _ := os.UserHomeDir()
	return filepath.Join(home, ".local", "share", "printing-press-golden-pp-cli", "data.db")
}
// Note: MCP tools use their own dbPath() because they are in a separate package (main, not cli).
// The CLI's defaultDBPath() in the cli package uses the same canonical path.

func handleSync(ctx context.Context, req mcplib.CallToolRequest) (*mcplib.CallToolResult, error) {
	return mcplib.NewToolResultText("sync not yet implemented via MCP - use the CLI: printing-press-golden-pp-cli sync"), nil
}

func handleSQL(ctx context.Context, req mcplib.CallToolRequest) (*mcplib.CallToolResult, error) {
	args := req.GetArguments()
	query, ok := args["query"].(string)
	if !ok || query == "" {
		return mcplib.NewToolResultError("query is required"), nil
	}

	// Block write operations
	upper := strings.ToUpper(strings.TrimSpace(query))
	for _, prefix := range []string{"INSERT", "UPDATE", "DELETE", "DROP", "ALTER", "CREATE"} {
		if strings.HasPrefix(upper, prefix) {
			return mcplib.NewToolResultError("only SELECT queries are allowed"), nil
		}
	}

	db, err := store.Open(dbPath())
	if err != nil {
		return mcplib.NewToolResultError(fmt.Sprintf("opening database: %v", err)), nil
	}
	defer db.Close()

	rows, err := db.Query(query)
	if err != nil {
		return mcplib.NewToolResultError(fmt.Sprintf("query failed: %v", err)), nil
	}
	defer rows.Close()

	cols, _ := rows.Columns()
	var results []map[string]any
	for rows.Next() {
		values := make([]any, len(cols))
		ptrs := make([]any, len(cols))
		for i := range values {
			ptrs[i] = &values[i]
		}
		rows.Scan(ptrs...)
		row := make(map[string]any)
		for i, col := range cols {
			row[col] = values[i]
		}
		results = append(results, row)
	}

	data, _ := json.MarshalIndent(results, "", "  ")
	return mcplib.NewToolResultText(string(data)), nil
}

func handleContext(_ context.Context, _ mcplib.CallToolRequest) (*mcplib.CallToolResult, error) {
	ctx := map[string]any{
		"api":         "printing-press-golden",
		"description": "Purpose-built fixture for golden generation coverage.",
		"archetype":   "project-management",
		"tool_count":  7,
		// tool_surface tells agents which surface a capability lives on so
		// they don't try to invoke cli_only_capabilities through MCP.
		"tool_surface": "MCP exposes the endpoints listed under `resources` (plus sync/search/sql/context utilities when present). Items under `cli_only_capabilities` require running the companion printing-press-golden-pp-cli binary; the MCP cannot invoke them.",
		"auth": map[string]any{
			"type": "api_key",
			"env_vars": []string{"PRINTING_PRESS_GOLDEN_API_KEY_AUTH",  },
		},
		"resources": []map[string]any{
			{
				"name": "projects",
				"description": "Manage projects",
				"endpoints": []string{"create", "get", "list",  },
				"syncable": true,
				"searchable": true,
			},
			{
				"name": "public",
				"description": "Manage public",
				"endpoints": []string{"get-status",  },
			},
			{
				"name": "reports",
				"description": "Manage reports",
				"endpoints": []string{ },
			},
		},
		"query_tips": []string{
			"Pagination uses cursor-based paging. Pass cursor parameter for subsequent pages.",
			"Control page size with the limit parameter (default 100).",
			"Use the sql tool for ad-hoc analysis on synced data. Run sync first to populate the local database.",
			"Use the search tool for full-text search across all synced resources. Faster than iterating list endpoints.",
			"Prefer sql/search over repeated API calls when the data is already synced.",
		},
		"playbook": []map[string]string{
			{"topic": "Finding stale work", "insight": "Use the stale command or sql query to find items not updated recently. More reliable than scanning list results manually."},
			{"topic": "Load analysis", "insight": "When analyzing team workload, filter by assignee and status. Raw counts without status filtering are misleading."},
			{"topic": "Bulk operations", "insight": "For bulk status changes, prefer update endpoints over delete+create. Most PM APIs track history on updates."},
		},
	}
	data, _ := json.MarshalIndent(ctx, "", "  ")
	return mcplib.NewToolResultText(string(data)), nil
}
