package patch

import (
	"bytes"
	"fmt"
	"os"
	"path/filepath"
)

// detectCollisions scans the CLI directory and root.go source for conflicts
// with the symbols PR #218 introduces. Returns all collisions; the caller
// decides which are fatal.
//
// A resource-level collision (existing profile.go / deliver.go / feedback.go
// whose content doesn't match the PR #218 drop-in) is fatal — patching would
// overwrite a working spec-derived capability. An already-patched CLI
// (matching drop-in content) is not a collision, it's idempotency.
func detectCollisions(dir string, rootSrc []byte) ([]Collision, error) {
	var collisions []Collision

	cliDir := filepath.Join(dir, "internal", "cli")
	for _, name := range []string{"profile.go", "deliver.go", "feedback.go"} {
		path := filepath.Join(cliDir, name)
		data, err := os.ReadFile(path)
		if err != nil {
			if os.IsNotExist(err) {
				continue
			}
			return nil, fmt.Errorf("reading %s: %w", path, err)
		}
		// A file bearing the printing-press generator header is known to be
		// from a prior patch run or a PR #218 regenerate — not a collision.
		if bytes.Contains(data, []byte("Generated by CLI Printing Press")) &&
			bytes.Contains(data, []byte("DO NOT EDIT")) {
			// Additionally check that it references the expected PR #218
			// symbols so an unrelated generated file doesn't get a free pass.
			if looksLikePR218Dropin(name, data) {
				continue
			}
		}
		collisions = append(collisions, Collision{
			Kind:    "resource",
			Symbol:  name[:len(name)-3], // strip ".go"
			File:    path,
			Message: fmt.Sprintf("%s already exists and is not a PR #218 drop-in — refusing to overwrite", path),
		})
	}

	return collisions, nil
}

// looksLikePR218Dropin returns true when the file content matches the
// signature of the template output for profile/deliver/feedback. Cheap
// heuristic: check for the canonical function name each template defines.
func looksLikePR218Dropin(filename string, data []byte) bool {
	switch filename {
	case "profile.go":
		return bytes.Contains(data, []byte("func newProfileCmd(")) &&
			bytes.Contains(data, []byte("func GetProfile("))
	case "deliver.go":
		return bytes.Contains(data, []byte("type DeliverSink")) &&
			bytes.Contains(data, []byte("func ParseDeliverSink("))
	case "feedback.go":
		return bytes.Contains(data, []byte("func newFeedbackCmd(")) &&
			bytes.Contains(data, []byte("type FeedbackEntry"))
	}
	return false
}
